# Generated by Django 5.1.2 on 2024-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_delete_countlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="should_be_completed_by_date",
            field=models.DateTimeField(null=True),
        ),
    ]
