# Generated by Django 5.1.2 on 2024-10-22 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_should_be_completed_by_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="should_be_completed_by_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 22, 0, 50, 19, 6327)
            ),
            preserve_default=False,
        ),
    ]
