# Generated by Django 5.1.2 on 2024-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_should_be_completed_by_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
