# Generated by Django 5.1.2 on 2024-10-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0007_todo_placeholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="placeholder",
        ),
    ]
